version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.0
  pre_build: # commands to be run before build
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      # login to Elastic container registry
      #- eval $(aws ecr get-login --region eu-north-1 --no-include-email | sed 's|https://||')
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 690578247312.dkr.ecr.eu-north-1.amazonaws.com
      - REPOSITORY_URI=690578247312.dkr.ecr.eu-north-1.amazonaws.com/bburim/laraws
      - IMAGE_TAG=1.0
  build:
    commands:
      - echo $REPOSITORY_URI
      - echo $IMAGE_TAG
      - echo Build started on `date`
      - echo installing composer..
      - composer install
      - echo creating .env file..
      - cp .env.example .env
      - echo generating app key
      - php artisan key:generate
      - php artisan cache:clear
      - php artisan config:clear
#      - php artisan migrate --force
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image ls -a
      - docker push $REPOSITORY_URI:$IMAGE_TAG
